# Generated by Django 2.1.3 on 2018-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
